### ISSUE TITLE
a little question

### ISSUE THREAD

**Issue by gaorong** [prydonius/mariadb-broker#4]
thanks for you awesome demo, everything is ok, but I have a question is why we use mariaDB by service catalog? what benefits can we obtain?  why not connect to the mariaDB host directly ? which seems more easily.

**Comment by prydonius** [comment]
Good question, I picked MariaDB mostly for demonstrative purposes. Usually, you'd want to use the Service Catalog to connect to an external database provider (e.g. Amazon RDS, Azure SQL), and this demonstrates the idea of dynamically provisioning a database instance and getting the credentials to connect to it.

This is also valuable if you wanted to use an external database in production, but wanted something simpler (such as this single-node MariaDB instance) in development. This gives you the exact same interface for connecting to the database (via secret values) between production and development so you don't need to worry about different configurations for the different environments.

**Comment by gaorong** [comment]
got it, thank U
